config/routes.rb
require 'subdomain'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'waitlists#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount AudioUploader::UploadEndpoint, at: 'upload/audio'
  mount ImageUploader::UploadEndpoint, at: 'upload/image'

  resources :charts, only: :index
  resources :home, only: :index
  resources :users

  resource :session, only: [:new, :create, :destroy] do
    get :profile, on: :member
  end

  resources :password_resets, except: [:index, :show, :destroy]
  resources :likes,   only: [:create, :update, :destroy]

  resource :profile,  only: [:show, :update]
  resource :waitlist, only: [:create, :update, :index]

  resources :soundbites, except: [:show]
  resources :battleground
  resources :stores
  resources :notifications

  resources :comments do
    get 'usernames', on: :member
  end

  resources :artists do
    get :viewer_side_unpopulated
    get :user_side_about
    get :user_side_first_time
    get :viewer_side_populated
    get :track_list
  end

  constraints(Subdomain) do
    get '/'     => 'artists#show'
    get '/edit' => 'artists#edit'
  end

  resources :conversations do
    resources :messages do
      collection do
        post :typing
      end
    end

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :beats, only: :index

  get '/callback' => 'sessions#callback'
  get '/soundcloud' => 'sessions#soundcloud'
  get '/auth/:provider/callback' => 'sessions#callback', as: :auth_callbacks
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/waitlist/:token/activate', to: 'waitlists#update'
  get '/waitlists/email_confirm'
  get '/waitlists/share'

  get '/invite/:referrer_id', to: 'waitlists#index', as: :invite_member

  resources :tracks do
    resources :comments
  end

  resources :soundcloud_tracks

  get 'critiques/:track_id' => 'critiques#show', as: :critique

  get 'ratings/create' => 'ratings#create_or_update'

  get '/sync' => 'tracks#sync'

  post 'beats/toggle_marked/:track_id' => 'tracks#update'
  get 'like/:track/:star' => 'ratings#create_or_update', as: :cou_like

  get '/:id' => 'shortener/shortened_urls#show'
  get 'beats/:track_id/social_share' => 'beats#social_share', as: :social_share

  namespace :admin do
    resource :dashboard, only: :show
    resource :session, only: [:new, :create, :destroy]
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USER'] && password == ENV['SIDEKIQ_PASSWORD']
  end if Rails.env.production? || Rails.env.staging?
  mount Sidekiq::Web, at: '/sidekiq/dashboard'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout false

  def index
    @conversations = current_user.mailbox.conversations
  end

  def inbox
    @conversations = current_user.mailbox.inbox
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash
    render action: :index
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/views/conversations/index.html.slim
h1 Conversations

hr
span
  |Inbox
  = "(#{current_user.mailbox.inbox.unread(current_user).count}) | "
  |All conversations
  = "(#{current_user.mailbox.conversations.count}) | "
  |Sent
  = "(#{current_user.mailbox.sentbox.count}) | "
  |Trash
  = "(#{current_user.mailbox.trash.count}) | "
hr

hr
span
  |Total:
  = @conversations.count

- @conversations.each do |conversation|
  div
    - if conversation.is_unread?(current_user)
      strong = link_to conversation.subject, conversation_path(conversation)
    - else
      = link_to conversation.subject, conversation_path(conversation)
br
hr
= link_to "new conversation", new_conversation_path

app/views/conversations/new.html.slim
h1 New conversation
= form_tag conversations_path, method: :post
  div
    = select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name)
  div
    = text_field_tag :subject, nil, placeholder: "Subject"
  div
    = text_area_tag :body, nil, placeholder: "Leave a comment"

  = submit_tag
= javascript_include_tag 'application'

app/views/conversations/show.html.slim
= javascript_include_tag 'application'
= csrf_meta_tags

= @conversation.subject
br
br
ul.all_messages
  - @conversation.receipts_for(current_user).each do |receipt|
    li = "<span style='color: #aaa;'>#{receipt.message.created_at.strftime("%H:%M")}</span> #{receipt.message.sender.name}: #{receipt.message.body}".html_safe 
    hr
br
.user_typing
= form_tag conversation_messages_path(@conversation), remote: true, method: :post do
  = hidden_field_tag :authenticity_token, form_authenticity_token
  div
    = text_area_tag :body
  = submit_tag