config/routes.rb
require 'subdomain'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'waitlists#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount AudioUploader::UploadEndpoint, at: 'upload/audio'
  mount ImageUploader::UploadEndpoint, at: 'upload/image'

  resources :charts, only: :index
  resources :home, only: :index
  resources :users

  resource :session, only: [:new, :create, :destroy] do
    get :profile, on: :member
  end

  resources :password_resets, except: [:index, :show, :destroy]
  resources :likes,   only: [:create, :update, :destroy]

  resource :profile,  only: [:show, :update]
  resource :waitlist, only: [:create, :update, :index]

  resources :soundbites, except: [:show]
  resources :battleground
  resources :stores
  resources :notifications

  resources :comments do
    get 'usernames', on: :member
  end

  resources :artists do
    get :viewer_side_unpopulated
    get :user_side_about
    get :user_side_first_time
    get :viewer_side_populated
    get :track_list
  end

  constraints(Subdomain) do
    get '/'     => 'artists#show'
    get '/edit' => 'artists#edit'
  end

  resources :conversations do
    resources :messages do
      collection do
        post :typing
      end
    end

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :beats, only: :index

  get '/callback' => 'sessions#callback'
  get '/soundcloud' => 'sessions#soundcloud'
  get '/auth/:provider/callback' => 'sessions#callback', as: :auth_callbacks
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/waitlist/:token/activate', to: 'waitlists#update'
  get '/waitlists/email_confirm'
  get '/waitlists/share'

  get '/invite/:referrer_id', to: 'waitlists#index', as: :invite_member

  resources :tracks do
    resources :comments
  end

  resources :soundcloud_tracks

  get 'critiques/:track_id' => 'critiques#show', as: :critique

  get 'ratings/create' => 'ratings#create_or_update'

  get '/sync' => 'tracks#sync'

  post 'beats/toggle_marked/:track_id' => 'tracks#update'
  get 'like/:track/:star' => 'ratings#create_or_update', as: :cou_like

  get '/:id' => 'shortener/shortened_urls#show'
  get 'beats/:track_id/social_share' => 'beats#social_share', as: :social_share

  namespace :admin do
    resource :dashboard, only: :show
    resource :session, only: [:new, :create, :destroy]
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USER'] && password == ENV['SIDEKIQ_PASSWORD']
  end if Rails.env.production? || Rails.env.staging?
  mount Sidekiq::Web, at: '/sidekiq/dashboard'
end

app/models/user.rb
class User < ActiveRecord::Base
  include VerifierConcern

  mount_base64_uploader :avatar, AvatarUploader
  mount_base64_uploader :background_image, BackgroundImageUploader
  acts_as_messageable

  enum roles: [:user, :admin]

  has_many :comments,   dependent: :destroy
  has_many :tracks,     dependent: :destroy
  has_many :ratings,    dependent: :destroy
  has_many :identities, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id
  has_many :track_comments, -> { where(commentable_type: 'Track') }, class_name: Comment
  has_many :commented_tracks, -> { uniq }, through: :track_comments, source: :commentable, source_type: Track

  validates :email,     uniqueness: true, presence: true
  validates :email,     format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :username,  uniqueness: true, length: { minimum: 4 }, presence: true
  validates :username,  format: { with: /\A^[a-zA-Z][-a-zA-Z0-9_.]+\Z/ }
  validates :first_name, :last_name, :city, :country, presence: true
  validates :password,  presence: true, if: -> { password_digest.blank? }
  validates :password,  length: { minimum: 8 }, if: -> { password.present? }

  has_secure_password

  recommends :tracks

  before_like      :increase_rating
  before_undislike :increase_rating
  before_unlike    :decrease_rating
  before_dislike   :decrease_rating
  before_create :generate_auth_token

  after_save :confirm_email
  after_create :set_default_avatar

  def increase_rating(track)
    rating = track.rating + 1
    update_rating(track, rating)
  end

  def decrease_rating(track)
    rating = track.rating - 1
    update_rating(track, rating)
  end

  def update_rating(track, rating)
    total_shares = track.permalink ? SocialShares.total(track.permalink) : 0

    rating += track.social_shares >= total_shares ? track.social_shares - total_shares : total_shares

    track.update(rating: rating, social_shares: total_shares)
  end

  def self.fetch_identity(identity_params, user_params)
    identity = Identity.find_by_provider_uid(identity_params[:provider], identity_params[:uid]).first
    user = identity&.user
    if user
      user.update(user_params)
      identity.update(identity_params)
      return user
    end
    user = new(user_params)
    user.save(validate: false)
    user.identities.create(identity_params)
    user
  end

  def confirm!
    update_column(:confirmed, true)
  end

  def name
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(_object)
    nil
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save(validate: false)
    UserMailer.reset_password(self).deliver_later
  end

  def generate_token(column)
    loop do
      self[column] = SecureRandom.urlsafe_base64
      break unless User.exists?(column => self[column])
    end
  end

  def generate_auth_token
    self.auth_token = SecureRandom.urlsafe_base64
  end

  def tester_id
    identity = identities.find_by(provider: 'prefinery')
    return raise StandardError, 'No Prefinery identity found.' unless identity
    identity.uid
  end

  def current_tester?
    identities.where(provider: 'prefinery').present? && identities.find_by(provider: 'prefinery').uid.present?
  end

  def position
    identities.find_by(provider: 'prefinery') ? identities.find_by(provider: 'prefinery').access_token : '2500'
  end

  def missing_password?
    password_digest.blank? || %i(password password_confirmation).any? { |a| errors.include?(a) }
  end

  def check_uniq_email
    valid?
    self.email = nil if errors.include?(:email)
  end

  def artist_info
    [username, city, country].join(', ')
  end

  def track_count
    tracks.count
  end

  private

  def confirm_email
    if changed.include?('email')
      token = verifier.generate(id: id)
      update_column(:confirmed, false)
      UserMailer.confirmation(self, token).deliver_later
    end
  end

  def set_default_avatar
    unless self[:avatar].present?
      assign_attributes(avatar: data_default_avatar)
      save(validate: false)
    end
  end

  def data_default_avatar
    regex = %r{\Adata:([-\w]+\/[-\w\+\.]+)?;base64,(.*)\Z}
    data_uri_parts = Identicon.data_url_for(username, 300).match(regex)
    title = username || 'user_avatar'
    file = Tempfile.new(title, encoding: 'ascii-8bit')
    file.write(Base64.decode64(data_uri_parts[2]))
    ActionDispatch::Http::UploadedFile.new(tempfile: file.open, filename: title, type: data_uri_parts[1])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :only_admin

  def index
    @user = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update]
  skip_before_filter :verify_authenticity_token
  skip_before_filter :check_valid_user

  def index; end

  def new
    @user = User.new
  end

  def create
    @agree = params[:agree]
    @user = User.new(user_params)
    render :new unless @user.save
  end

  def edit
    if @user
      @user.confirm!
      sign_in(@user)
    end
    redirect_to home_index_path
  end

  def update
    if params[:provider].present?
      @user.update(user_params)
      @avatar_data = params[:user][:avatar]
    elsif @user.update(user_params)
      redirect_to home_index_path
    else
      render :edit
    end
  end

  private

  def find_user
    @user = current_user || User.find(user_verifier[:id])
  end

  def user_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :email, :country,
                                 :username, :city, :password, :password_confirmation)
  end

  def user_verifier
    verifier.verify(params[:token])
  end
end

app/views/users/_form.html.slim
.logins class="#{'hide' if user.errors.present?}"
  .unique-login
    h4 Sign up With Email
    a.button.email
      i.fa.fa-envelope

  .social-login
    h4 Or Connect With
    = link_to soundcloud_path, class: 'button social soundcloud' do
      i.fa.fa-soundcloud
    = link_to '/auth/twitter', class: 'button social twitter' do
      i.fa.fa-twitter
fieldset.form-create-account class="#{'hide' unless user.errors.present?}"
  legend CREATE ACCOUNT
  hr
  = simple_form_for user, html: { id: 'sign-up-form' }, data: { remote: true }, defaults: { input_html: { class: 'input-form' } } do |f|
    .form-user.show
      = f.input_field :first_name, label: false, placeholder: 'First Name', autofocus: true, 'data-parsley-required-message' => "first name required"
      = f.full_error :first_name
      = f.input_field :last_name, label: false, placeholder: 'Last Name', autofocus: true, 'data-parsley-required-message' => "last name required"
      = f.full_error :last_name
      = f.input_field :city, label: false, placeholder: 'City', autofocus: true, 'data-parsley-required-message' => "City required"
      = f.full_error :city
      = f.input_field :country, priority: ['United States']
      = f.full_error :country
      = checkbox_default('agree', 'Agree to terms & conditions', value: true, checked: @agree, data: {'parsley-required' => "true", 'parsley-required-message' => "Agreement required" })
      a.next-form
        = 'Next'

    .form-user.hide
      = f.input_field :email, label: false, placeholder: 'Email', autofocus: true, 'data-parsley-required-message' => "email required"
      = f.full_error :email
      = f.input_field :password, label: false, placeholder: 'Password', autofocus: true, 'data-parsley-required' => "true", 'data-parsley-required-message' => "password required", 'data-parsley-minlength' => "8", 'data-parsley-minlength-message' => "password should have min 8 characters"
      = f.full_error :password
      = f.input_field :password_confirmation, label: false, placeholder: 'Password (must match above)', autofocus: true, 'data-parsley-required' => "true", 'data-parsley-required-message' => "password confirmation required", 'data-parsley-equalto'=> "#user_password", 'data-parsley-equalto-message' => "password doesn't match"
      = f.full_error :password_confirmation
      = f.input_field :username, label: false, placeholder: 'Choose username', autofocus: true,  pattern: "^[a-zA-Z][a-zA-Z0-9_-]+$", 'data-parsley-minlength' => "4", 'data-parsley-required-message' => "username required", 'data-parsley-minlength-message' => "username should have min 4 characters"
      = f.full_error :username
      = f.button :button, 'Next', data: { disable_with: spinner_loader }, class: 'next-form'

app/views/users/create.js.slim
| $.lazybox.close();
| window.location = "#{root_path}";

app/views/users/edit.html.slim
= simple_form_for @user do |f|
  = f.input_field :first_name, label: false, placeholder: 'First Name', autofocus: true
  = f.input_field :last_name, label: false, placeholder: 'Last Name', autofocus: true
  = f.input_field :city, label: false, placeholder: 'City', autofocus: true
  = f.input_field :country, priority: ['United States']
  = f.input_field :email, label: false, placeholder: 'Email', autofocus: true
  = f.input_field :password, label: false, placeholder: 'Password', autofocus: true
  = f.input_field :password_confirmation, label: false, placeholder: 'Password (must match)', autofocus: true
  = f.input_field :username, label: false, placeholder: 'Username', autofocus: true
  = f.button :submit, 'Submit', class: 'button submit inactive'

app/views/users/new.js.slim
| $.lazybox("#{j(render partial: 'form', locals: {user: @user})}");
| $('#sign-up-form').parsley({successClass: "has-success", errorClass: "has-error"});
- if @user.errors.present?
  | $('.form-create-account .form-user').addClass( 'hide' ).removeClass( 'show' );
  | $('.form-create-account span.error').first().parents('.form-user').removeClass( 'hide' ).addClass( 'show' );

app/views/users/update.js.slim
- if @user.errors.present?
  | $.lazybox("#{j(render partial: 'sessions/profile_form', locals: {user: @user, avatar_data: @avatar_data})}", {esc: false, close: false, modal: true, klass: 'twitter-modal'});
  | $("#inputFile").change(function () { readURL(this); });
  | $('form.simple_form.edit_user .profile-form').addClass( 'hide' );
  | $('form.simple_form.edit_user .error').first().parents('.profile-form').removeClass( 'hide' );
  - if @avatar_data
    | $('#image_upload_preview').attr('src', "#{@avatar_data}")
- else
  | $.lazybox.close();
  | window.location = "#{home_index_path}"