config/routes.rb
require 'subdomain'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'waitlists#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount AudioUploader::UploadEndpoint, at: 'upload/audio'
  mount ImageUploader::UploadEndpoint, at: 'upload/image'

  resources :charts, only: :index
  resources :home, only: :index
  resources :users

  resource :session, only: [:new, :create, :destroy] do
    get :profile, on: :member
  end

  resources :password_resets, except: [:index, :show, :destroy]
  resources :likes,   only: [:create, :update, :destroy]

  resource :profile,  only: [:show, :update]
  resource :waitlist, only: [:create, :update, :index]

  resources :soundbites, except: [:show]
  resources :battleground
  resources :stores
  resources :notifications

  resources :comments do
    get 'usernames', on: :member
  end

  resources :artists do
    get :viewer_side_unpopulated
    get :user_side_about
    get :user_side_first_time
    get :viewer_side_populated
    get :track_list
  end

  constraints(Subdomain) do
    get '/'     => 'artists#show'
    get '/edit' => 'artists#edit'
  end

  resources :conversations do
    resources :messages do
      collection do
        post :typing
      end
    end

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  resources :beats, only: :index

  get '/callback' => 'sessions#callback'
  get '/soundcloud' => 'sessions#soundcloud'
  get '/auth/:provider/callback' => 'sessions#callback', as: :auth_callbacks
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/waitlist/:token/activate', to: 'waitlists#update'
  get '/waitlists/email_confirm'
  get '/waitlists/share'

  get '/invite/:referrer_id', to: 'waitlists#index', as: :invite_member

  resources :tracks do
    resources :comments
  end

  resources :soundcloud_tracks

  get 'critiques/:track_id' => 'critiques#show', as: :critique

  get 'ratings/create' => 'ratings#create_or_update'

  get '/sync' => 'tracks#sync'

  post 'beats/toggle_marked/:track_id' => 'tracks#update'
  get 'like/:track/:star' => 'ratings#create_or_update', as: :cou_like

  get '/:id' => 'shortener/shortened_urls#show'
  get 'beats/:track_id/social_share' => 'beats#social_share', as: :social_share

  namespace :admin do
    resource :dashboard, only: :show
    resource :session, only: [:new, :create, :destroy]
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USER'] && password == ENV['SIDEKIQ_PASSWORD']
  end if Rails.env.production? || Rails.env.staging?
  mount Sidekiq::Web, at: '/sidekiq/dashboard'
end

app/views/shared/_desktop_nav.slim
#desktop-navigation
  nav.navbar
    .navbar__group
      .navbar__item
        = link_to home_index_path do
          = image_tag "BT-logo.1.svg"
      .navbar__item
        = link_to_unless_current 'Beats',   beats_path do
          span Beats
      .navbar__item
        = link_to_unless_current 'Charts', charts_path do
          span Charts
      .navbar__item
        = link_to_unless_current 'Battleground', battleground_index_path do
          span Battleground
    .navbar__group.navbar__group--right
      - if current_user
        .navbar__item = link_to 'Upload', new_track_path
        .navbar__item
          a href="#"
            i.fa.fa-comment aria-hidden="true"
        .navbar__item
          a href="#"
            i.fa.fa-music aria-hidden="true"
        .navbar__item.navbar__item--avatar
          = link_to profile_path do
            = user_avatar(current_user)
        .dropdown
          label for="drop"
          input type='checkbox' id="drop"
          .dropdown__content
            .dropdown__top
              span = current_user.name
              .dropdown__right-group
                = link_to profile_path do
                  = user_avatar(current_user)
                label
            .dropdown__center
              = link_to 'profile', profile_path
              = link_to 'my artist page', artist_track_list_path(artist_id: current_user.id)
              = link_to 'product', 'javascript:void(0);'
              = link_to 'settings', 'javascript:void(0);'
              = link_to 'sign out', signout_path
            .dropdown__bottom
              = link_to 'Legal', 'javascript:void(0);'
              = link_to 'Copyright', 'javascript:void(0);'
              = link_to 'Help', 'javascript:void(0);'

      - else
        .navbar__item = link_to :sign_in, signin_path, remote: true
        .navbar__item.navbar__item--btn = link_to :sign_up, signup_path, remote: true

app/views/shared/_desktop_slider.slim
.d-slide
  .flexslider
    .sliderlogo-bar.new-slider-logo
      - if params[:profile].present?
        = link_to '', profile_session_path(provider: params[:profile]), remote: true, id: 'profile-link'
      a href="#"
        = image_tag "/assets/beat-logo-bar.png"
    ul.slides
      li
        img src="assets/slider-1.jpg" /
        p Get feedback on your music.
      li
        img src="assets/slider-2.jpg" /
        p Be seen by top producers.
      li
        img src="assets/slider-3.jpg" /
        p Enter producer contests
      li
        img src="assets/slider-4.jpg" /
        p Get your own artist page

app/views/shared/_form_error.slim
.uk-alert.uk-alert-danger data-uk-alert=""
  a.uk-alert-close.uk-close
  p

app/views/shared/_messages.slim
- flash.each do |key, value|
  - if key == "notice"
    - key = :info
  - elsif key == "danger"
    - key = :error
  - elsif key == "alert"
    - key = :error
  javascript:
    toastr.#{key}("#{value}");

app/views/shared/_mobile_beats.slim
- @tracks.each do |track|
  .mobile-beats-section
  .columns
    .column.is-12
      .beat-list-mobile
        .beat-mobile-header
          .media-left
            .icon-lg
              span.verified-icon
                img alt=("Verified crown") src="/assets/verified-crown.svg" /
              = image_tag '/assets/chris.png'
          .media-body
            h6 Chris Keys
            p Sour Masch

        .beat-mobile-content
          .beats-show
            a href="#" 
              .fill-1
                i#play-btn-1.fa.fa-play.play-btn
            = image_tag '/assets/artist-bg-img.png'
          .beats-rating-list id="ratelist_#{track.id}"
            ul.top-list
              li
                = rating_link track.id, 'fire', 'like'
                span id="like_#{track.id}"
                  | #{track.like_count}
              li
                = rating_link track.id, 'sad', 'indifferent'
                span id="indifferent_#{track.id}"
                  | #{track.indifferent_count}
              li
                = rating_link track.id, 'unlike', 'dislike'
                span id="dislike_#{track.id}"
                  | #{track.dislike_count}
          .beats-critique-mobiletab id="mobile_critique_tabs_#{track.id}"
            ul.mobile-tabs-menu
              li.current
                a href="#mobile-tab-1"  Critique
              li
                a href="#mobile-tab-2"  Contact
              li
                a href="#mobile-tab-3"  Info
              li
                a href="#mobile-tab-4"
                  = image_tag '/assets/share.svg'
            .mobile-tab
              #mobile-tab-1.mobile-tab-content
                span.hidden.mobile-critique-info
                  = link_to 'More By This Artist',artist_track_list_path(track.artist_type.try(:id) || 'Error')
                  = link_to 'See All Critiques', critiques_path
                = form_for :comment, html: {id: "form_#{track.id}"} do |f|
                  = hidden_field_tag :track_id, track.id
                  = f.text_area :body, placeholder: 'Write your critique here', class: 'textarea'
                span.counter
                  -if current_user
                    a class='send-button' href="#-" onclick=("send_comment(#{track.id});return false") id="send_#{track.id}" Send
                  -else
                    a class='send-button' href="#-" id="send_#{track.id}" Send
              #mobile-tab-2.mobile-tab-content
                p Donec semper dictum sem, quis pretium sem malesuada non. Proin venenatis orci vel nisl porta sollicitudin. 
              #mobile-tab-3.mobile-tab-content
                p Duis egestas fermentum ipsum et commodo. Proin bibendum consectetur elit, hendrerit porta mi dictum eu.
              #mobile-tab-4.mobile-tab-content
                p Proin sollicitudin tincidunt quam, in egestas dui tincidunt non. Maecenas tempus condimentum mi, sed convallis tortor iaculis eu.

        .beat-mobile-footer
          ul
            li
              a id="rate_tab_#{track.id}" href="#"
                span.rate-link id="#{track.id}" rate
                span.rate-link-close id="#{track.id}" 
                 = image_tag '/assets/close.png'
            li
              a id="critique_tab_#{track.id}" href="#"
                span.critique-link id="#{track.id}" critique
                span.critique-link-close id="#{track.id}" 
                 = image_tag '/assets/close.png'


            
javascript:
  $(document).ready(function(){
    $(".mobile-tabs-menu a").click(function(event) {
        event.preventDefault();
        $(this).parent().addClass("current");
        $(this).parent().siblings().removeClass("current");
        var tab = $(this).attr("href");
        $(".mobile-tab-content").not(tab).css("display", "none");
        $(tab).fadeIn();
    });

    $(".beats-rating-list").hide();
    $(".beats-critique-mobiletab").hide();

    $(".rate-link").click(function(){
      track_id = this.id
      $("#critique-tab").removeClass('close-tab-icon');
      $(".beats-show").hide();
      $(".beats-critique-mobiletab").hide();
      $("#rate_tab_"+track_id).addClass('close-tab-icon');
      $("#ratelist_"+track_id).show();
    });
    
    $(".rate-link-close").click(function(){
      $(".beats-critique-mobiletab").hide();
      $(".beats-rating-list").hide();
      $("#rate-tab").removeClass('close-tab-icon');
      $(".beats-show").show();
    });

    $(".critique-link").click(function(){
      track_id = this.id
      $("#rate_tab_"+track_id).removeClass('close-tab-icon');
      $(".beats-show").hide();
      $(".beats-rating-list").hide();
      $("#critique_tab_"+track_id).addClass('close-tab-icon');
      $("#mobile_critique_tabs_"+track_id).show();
    });

    $(".critique-link-close").click(function(){
      track_id = this.id
      $(".beats-rating-list").hide();
      $("#mobile_critique_tabs_"+track_id).hide();
      $("#critique_tab_"+track_id).removeClass('close-tab-icon');
      $(".beats-show").show();
    });
    
  });

app/views/shared/_mobile_nav.slim
#mobile-navigation
  nav.main-nav.main-nav-bg.nav
    ul.mobile-header
      li 
        a 
          i.fa.fa-bars#toggle-bar
        ul#toggle-bar-list
          li
            = link_to "Beats", beats_path
          li
            = link_to "Charts", charts_path
          li
            = link_to "Battleground", battleground_index_path
          
      li 
        a href="#{home_index_path}"
          = image_tag "/assets/BT-logo.1.svg", style: "width: 39px; height: 44px;"
      li
        a 
          span SIGN IN


javascript:
  $(document).ready(function(){
      $("#toggle-bar").click(function(){
          $("#toggle-bar-list").toggle();
      });
  });

app/views/shared/_mobile_slider.slim
.m-slide
  .mobile-logo
    img alt="" src="assets/mobile-logo.png" /     
  #caption-slide.slider-container
    .slider
      .slide
        img alt="" src="assets/mobile-slide1.png" /
        p Get feedback on your music.
      .slide
        img alt="" src="assets/mobile-slide2.png" /
        p Be seen by top producers.
      .slide
        img alt="" src="assets/mobile-slide3.png" /
        p Enter producer contests
      .slide
        img alt="" src="assets/mobile-slide4.png" /
        p Get your own artist page
  .mobile-create-account
    a.button.sign-up data-remote="true" href="/signup"  CREATE AN ACCOUNT

app/views/shared/_modal.slim
.modal id="#{id}"
	.modal-background
	.modal-container
		.modal-content
			.button-wrap
				.modal-box
					h1.modal-header = title
					.content
						= yield

				button.modal-close

app/views/shared/_modal2.html.slim
/ modal without close button
.modal id="#{id}"
	.modal-background
	.modal-container
			.modal-content
				.modal-box.modal-box-block
					h1.modal-header = title
					.content
						= yield

app/views/shared/_nav.slim
= render 'shared/desktop_nav'
= render 'shared/mobile_nav'

app/views/shared/_share_form.html.slim
.social-box.modal-social
	h5.title HOW WOULD YOU LIKE TO SHARE
	ul.getsocial
		li
			a href="https://twitter.com/intent/tweet?status=#{@track.title} + https://beatthread.com" class="share-button twitter" target="_blank"
				i class="uk-icon-twitter"
		li
			a href="http://www.facebook.com/sharer/sharer.php?u=https://beatthread.com&title=#{@track.title}" class="share-button facebook" target="_blank"
				i class="uk-icon-facebook"
		li
			a href="http://www.tumblr.com/share?v=3&u=https://beatthread.com&t=#{@track.title}" class="share-button tumblr" target="_blank"
				i class="uk-icon-tumblr"
		li
			a href="https://plus.google.com/share?url=https://beatthread.com" class="share-button googleplus" target="_blank"
				i class="uk-icon-google-plus"
		li
			a href="mailto:?Subject=#{@track.title} by #{@track.user.username}&amp;&Body=#{@track.description}" class=" email"
				i class="uk-icon-envelope"
		li
			a href="sms:?&body=" class=" sms"
				i class="uk-icon-comment"
	.text-right
		a class="uk-button uk-button-success uk-button-large btn-next" id="social-share-close" Done



javascript:
	$('#social-share-close').click(function() {
		$.lazybox.close();
	});
	


	$('.share-button').click(function() {
		window.open(this.href,'', "height=600 width=600  resizable=yes scrollbars=yes")
	});

app/views/shared/_slider.slim
= render 'shared/desktop_slider'
= render 'shared/mobile_slider'

javascript:
  window.onload=function(){
    if (document.getElementById('profile-link')!=null||document.getElementById('profile-link')!="") {
      jQuery('#profile-link').click();
    }
  }

  $("#slider-container").sliderUi({
    speed: 400,
    cssEasing: "cubic-bezier(0.285, 1.015, 0.165, 1.000)"
  });
  $("#caption-slide").sliderUi({
    caption: true
  });

  $(document).ready(function () {
    $('.flexslider').flexslider({
    animation: 'fade',
    controlsContainer: '.flexslider'
   });
  });

app/views/shared/_waveform.slim
ruby:
  cid = SecureRandom.hex

#waveform-proc data-id=("wf-#{cid}") data-url=(url) data-waveform=(data)
canvas id=("wf-#{cid}")